title: Tim Smith
subtitle: Senior Developer by day, bibliophile by night. Also known to make music and read poetry
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal site where I'll share anything I think could be of interest

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
# Disabling Gallery for the moment - I'm not a photographer. May come back with something another time
#    - text: Gallery
#      url: /gallery
#    - text: Shop
#      url : /shop
    - text: Contact Me
      url : /contact
#    - text: Styleguide
#      url: /styleguide
#    - text: Get Started
#      url: /get-started


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Tim Smith
author_bio: There are some who call me ... Tim. Once a journalist of sorts and now a coder of sorts. I also love music and medieval poetry.
author_email: "web_contact@aw7.uk"
author_location: UK
author_website_url: "http://timsmith714.github.io"
# Author Skills go in _includes/author_skills.html

# Experiences
author_work_experiences:
            - company_name: Arun Estates Ltd
              company_logo: office-business-icons/PNG/256/Organizing.png
              company_url: https://www.arunestates.co.uk
              designation: Senior Developer
              description: I manage the various websites and work on in house tools. I focus on Azure
              visibility: true
            - company_name: Computeractive
              company_logo: office-business-icons/PNG/256/Writing&Drinking.png
              company_url: https://www.computeractive.co.uk
              designation: Workshops Editor
              description: Wrote and edited the Workshops section of the magazine. During my time on the magazine I also wrote, presented and edited videos, managed the forums. Known as the 'Technical heart' of the magazine
              visibility: true

# Education
author_education_details:
              - college_logo: office-business-icons/PNG/256/Diploma.png
                college_name: University of Kent
                college_url: https://www.kent.ac.uk/
                college_degree: BA (hons) in History
                description: Upper 2nd class degree. 
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: office-business-icons/PNG/256/CTA.png
                project_title: Python
                project_description: Wrote a tool that, when given a product, created custom Facebook audiences based on website behaviour and assigned adverts
                project_url: 
                visibility: true
              - project_thumbnail: piers_plowman.png
                project_title: Piers piers_plowman
                project_description: Took some time, but I managed to read it all
                project_url:
                visibility: false


# social links
twitter_username: tr_smith
github_username:  TimSmith714
facebook_username: 
linkedin_username: timothyrichardsmith
behance_username: 
instagram_username: the_aardwolf
medium_username: 
telegram_username: 
dribbble_username: 
flickr_username: timsmith714

#for comments using disqus
disqus_shortname: 

# wakatime username (coding activity)
wakatime_username: 

# mailchimp embedded form url (newsletter):
mailchimp_form_url: 

# formspree (contact form)
formspree_email: timsmith714@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _DRAFTS

destination: ./build
